# Project information
site_name: 算法笔记
# site_url: https://cvenwu.github.io/mkdocs-material/
site_author: yirufeng
# site_description: >-
  # Write your documentation in Markdown and create a professional static site in
  # minutes – searchable, customizable, in 60+ languages, for all devices

# 设置右上角关联到的仓库
repo_name: cvenwu/AlgoBook
repo_url: https://github.com/cvenwu/AlgoBook

# 版权信息
copyright: Copyright &copy; 2016 - 2024 yirufeng

# 导航栏设置
nav:
  - Home: index.md
  - LeetCode:
    - 题目列表:
      - 1. 两数之和: leetcode/1_两数之和.md
      - 2235. 两整数相加: leetcode/2235_两整数相加.md
      - 2. 两数相加: leetcode/两数相加.md
      - License: leetcode/2.md
    - Tutorials:
      - template: template/template.md
      - tutorials/index.md
    - Changelog:
      - tx: changelog/index.md
  - 程序员面试金典:
    - setup/index.md
    - Changing the colors: setup/changing-the-colors.md
    - Extensions:
      - setup/extensions/index.md
      - Python Markdown: setup/extensions/python-markdown.md
  - 刷题总结: 
    - plugins/index.md
    - Requirements:
      - Caching: plugins/requirements/caching.md
  - Community:
    - Contributing:
      - contributing/index.md
      - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
    - Guides:
      - Creating a reproduction: guides/creating-a-reproduction.md
    - Community experts program:
      - insiders/community-experts-program/index.md
  - Blog:
    - blog/index.md

# 主题相关配置
theme:
  name: material
  language: zh
  icon:
    logo: material/library
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cvenwu
    - icon: fontawesome/solid/paper-plane
      link: mailto:yirufeng@foxmail.com

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/katex.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
